export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas – no fluff.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top – making your learning more organized.",
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description:
      "Beyond just answers – unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Real-Time Feedback",
    description:
      "Receive instant feedback on your answers to improve clarity, correctness, and confidence before real interviews.",
  },
  {
    id: "06",
    title: "Track Your Progress",
    description:
      "Visualize your learning journey with progress tracking and performance insights across all topics.",
  },
  {
    id: "07",
    title: "Practice with AI Interviewer",
    description:
      "Simulate real interview scenarios with an AI interviewer that adapts questions based on your performance.",
  },
];

export const CARD_BG = [
  { id: 1, bgcolor: "linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)" },
  { id: 2, bgcolor: "linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)" },
  { id: 3, bgcolor: "linear-gradient(135deg, #eaf7ff 0%, #f7fbff 100%)" },
  { id: 4, bgcolor: "linear-gradient(135deg, #fff2e9 0%, #fff9f4 100%)" },
  { id: 5, bgcolor: "linear-gradient(135deg, #f7f6f6 0%, #fafafa 100%)" },
  { id: 6, bgcolor: "linear-gradient(135deg, #f5fffb 0%, #f8fffb 100%)" },
  { id: 7, bgcolor: "linear-gradient(135deg, #f6eff3 0%, #fff8fc 100%)" },
  { id: 8, bgcolor: "linear-gradient(135deg, #e8fcef 0%, #f7fffb 100%)" },
  { id: 9, bgcolor: "linear-gradient(135deg, #feecff 0%, #fff5ff 100%)" },
  { id: 10, bgcolor: "linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)" },
];
